# Generated by Django 2.2 on 2019-05-05 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_bought',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
