# Generated by Django 2.2.1 on 2019-06-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190505_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='current_bought',
        ),
    ]
