# Generated by Django 2.2 on 2019-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='image',
            field=models.ImageField(blank=True, default='/shop/1.jpg', upload_to='products_pictures'),
        ),
    ]
