# Generated by Django 2.2 on 2019-04-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='luggage',
            options={'ordering': ['-created']},
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
    ]
