# Generated by Django 2.2 on 2019-04-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190429_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luggage',
            old_name='availiable',
            new_name='available',
        ),
    ]
