# Generated by Django 2.2 on 2019-05-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190509_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='image',
            field=models.ImageField(blank=True, default='products_pictures/default.jpg', upload_to='products_pictures'),
        ),
    ]
