# Generated by Django 2.2 on 2019-05-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190505_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggage',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='products_pictures'),
        ),
    ]
